### ISSUE TITLE
deepcopy()-ing QuerySet objects initializes them without args and breaks

### ISSUE THREAD

**Issue by ydaniv** [MnogoByte/django-permanent#28]
It breaks when `PermanentQuerySet.__init__()` adds query objects and looks for the model's `_meta` since `.model` is `None`.

I have a code base that depends on Django REST Framework. When upgrading from 2.4 to 3.0 this action is used heavily and everything breaks pretty badly.

**Comment by meteozond** [comment]
Thanks!
