### ISSUE TITLE
Defined behaviour for on_delete=models.SET_NULL

### ISSUE THREAD

**Issue by aidanlister** [MnogoByte/django-permanent#33]
What behaviour is expected for soft deleting? I'm guessing it forces it to DO_NOTHING ... but this creates inconsistencies in the data.

E.g two models, Task and Round. We have 100 tasks with a round_id=5 ... when we delete Round(5) task_id=5 but `task.round` throws an error.

**Comment by meteozond** [comment]
Some `on_delete` behaviour was fixed with #46 
Looks like it fixes your problem, is it?

**Comment by meteozond** [comment]
Looks like we've got consistent behaviour now, closing.
