### ISSUE TITLE
.updated not updated when object deleted

### ISSUE THREAD

**Issue by jarekwg** [MnogoByte/django-permanent#34]
.updated timestamp should probs be updated to now when an object is soft deleted.

**Comment by lciolecki** [comment]
Man, when we would expect release 1.1.6 version? :) I know that you don't have much of time.. But I'm waiting for fix #65 - this is really needed thing.

**Comment by aidanlister** [comment]
Any chance of getting this done?

**Comment by lciolecki** [comment]
This fix has been already released at version 1.1.6.

**Comment by jarekwg** [comment]
Ooh nice. Cheers,
