### ISSUE TITLE
set db_index=True in Defaults for FIELD_KWARGS

### ISSUE THREAD

**Issue by cancan101** [MnogoByte/django-permanent#43]
This should speed fetching up in the case where there are a fair number of deletes.

**Comment by meteozond** [comment]
It's good practice to keep your database clean, reducing number of shadow objects. More than that most cases require complex filtering and `together` indexes. Adding default redundant key will slow down insert and update queries. So it is up to you provide your own `PERMANENT_FIELD_KWARGS` settings with `db_index` if you need it.

**Comment by aidanlister** [comment]
This is crazy, the cost of adding an index here is essentially zero unless you're doing thousands of writes per second, the performance penalty is huge. It should at least have a huge warning in README that the default configuration is optimised for a use case most people will never encounter, and that they should start with this in their settings.py:

```
PERMANENT_FIELD_KWARGS = {
    'default': None,
    'null': True,
    'blank': True,
    'editable': False,
    'db_index': True,
}

```

**Comment by meteozond** [comment]
You are definitely right according to readme notice. Going to fix it soon.
