### ISSUE TITLE
django >= 1.6 ?

### ISSUE THREAD

**Issue by bashu** [MnogoByte/django-permanent#5]
Hey,

Is there reason why django-permanent depends on django >= 1.6 ? Is there something non back-compatible?

**Comment by meteozond** [comment]
Yes, there were some significant changes of QuerySet.delete method. You can use 0.1.4 [branch](https://github.com/meteozond/django-permanent/tree/0.1.4) or [package](https://pypi.python.org/pypi/django-permanent/0.1.4) for earlier Django versions.

**Comment by bashu** [comment]
Thanks! =)

**Comment by bashu** [comment]
BTW, 0.1.4 will not work with django==1.4.x, django.db.models.deletion.Collector  doesn't have 'fast_deletes' attribute

**Comment by meteozond** [comment]
Yep. You are right. Honestly, It's possible to group all tricks together to mimic Collector of several Django versions. But I'm thinking of starting with the 1.6.
Sorry.
