### ISSUE TITLE
django-permanent-helpers

### ISSUE THREAD

**Issue by bashu** [MnogoByte/django-permanent#61]
Hey,

Thanks for django-permanent app and here is my small contribution https://github.com/bashu/django-permanent-helpers

Q: is it worth mentioning in docs?

**Comment by meteozond** [comment]
Cool, looks like this is something like @cancan101 wanted in #64.
But I think there is better to provide separate model for soft deleted (something like Recycle Bin) with restoration and hard delete actions within.
Any way It deserves to mentioned in `README.rst`. May be you have any idea how to make it better. It will be great if PR will be provided.
