### ISSUE TITLE
TypeError: _clone() takes exactly 1 argument

### ISSUE THREAD

**Issue by deltadanger** [MnogoByte/django-permanent#62]
With Django 1.8, if I have a `PermanentModel` `MyModel` and I try to make a query like `MyModel.objects.all().values('my_field')`, it raises a `TypeError: _clone() takes exactly 1 argument`.
This is caused by the Django call from https://github.com/django/django/blob/stable/1.8.x/django/db/models/query.py#L1144.

Simply replacing your code at https://github.com/meteozond/django-permanent/blob/master/django_permanent/query.py#L128 with 
```
    def _clone(self, *args, **kwargs):
        c = super(BasePermanentQuerySet, self)._clone(*args, **kwargs)
```
will fix the issue.

**Comment by meteozond** [comment]
Yes Django provides separate queryset for values. Thanks. Fixed in 1.1.5
