### ISSUE TITLE
How CASCADE / SET_NULL should works for a "removed" PermanentModel?

### ISSUE THREAD

**Issue by bashu** [MnogoByte/django-permanent#74]
Consider following case:
```python
    def test_delete_for_removable_nullable_depended(self):
        model = RemovableNullableDepended
        dependend = model.objects.create(dependence=self.permanent)
        dependend.delete()
        self.permanent.delete()
        try:
            self.assertEqual(model.objects.first().dependence, None)
        except AttributeError:
            self.fail()
```

if I delete ``dependend`` before deleting ``self.permanent``, then ``dependence`` attribute will not be set to None. WAD or bug?

**Comment by bashu** [comment]
@meteozond sup?

**Comment by meteozond** [comment]
I've tried to implement same strategy as django does. So` dependence` have to be `null`-ed if `on_delete=models.SET_NULL` is set. So it is definitely bug. 
There is another problem - I've recently left @MnogoByte and transferred all open source projects I made there. So I'm not sure weather I've got enough authority to make any changes in this project today.
